theme = "soho"
baseurl = "https://vdmkenny.github.io/blog/"
languageCode = "en"
title = "Kenny's Lair"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "Kenny's Lair"
description = "Personal blog"
gravatar = "vdmkenny@gmail.com"
images = ["images/profile.png"]
# profilePicture = "images/profile.png"
copyright = "Kenny Van de Maele"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
themeColor = "#3f3f3f"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/kenny-van-de-maele-26558493/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/vdmkenny/"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
